### ISSUE TITLE
Use xarray.testing.assert_allclose

### ISSUE THREAD

**Issue by TomNicholas** [CWorthy-ocean/roms-tools#104]
Here we are using `np.allclose` over and over

https://github.com/CWorthy-ocean/roms-tools/blob/c1e89bee29a0bc3769bd09bdb99c2b674afeba37/roms_tools/tests/test_boundary_forcing.py#L396

but we could just compare the whole dataset at once using [`xarray.testing.assert_allclose`](https://docs.xarray.dev/en/stable/generated/xarray.testing.assert_allclose.html)

**Comment by NoraLoose** [comment]
I'm generally all for using `xr.testing.assert_allclose`. There are a few reasons why I didn't do it here:

- I want to make sure that an error is raised if the dimension order is not `s_`, `eta_`, `xi_` because this is the dimension order that ROMS assumes. `xarray` is insensitive to reordered dimensions.
- I'm actually not comparing the whole dataset because the computation of `BoundaryForcing` is terribly slow, even for a single time slice. (As is, the test is already taking up several minutes, which really slows down the entire test suite.) So I am skipping fields that are similar to others. This argument is more relevant here:
https://github.com/CWorthy-ocean/roms-tools/blob/c1e89bee29a0bc3769bd09bdb99c2b674afeba37/roms_tools/tests/test_boundary_forcing.py#L717-L723
where I do **not** call `ds.compute()` before the comparison.

I'm hoping we can improve performance by working on #43 soon, and then the second point will be irrelevant.

**Comment by NoraLoose** [comment]
BTW do you know an easy way to write an entire expected_ds into the test?

When I have `boundary_forcing.ds` in a notebook and do `print(boundary_forcing.ds)` it just shows a condensed version like
<img width="699" alt="Screenshot 2024-08-29 at 3 29 13 PM" src="https://github.com/user-attachments/assets/073be430-0e35-4550-91d8-4707c61ade7b">

I can't just copy / paste that.

**Comment by TomNicholas** [comment]
> BTW do you know an easy way to write an entire expected_ds into the test?

No - I mean the Dataset could point to an arbitrarily large amount of data so it's truncated quickly. In general I'm not a fan of hardcoding expected data values into the testing code...

**Comment by NoraLoose** [comment]
But having these tests with expected data values has proven really, really useful when refactoring the code. These are *the* tests that have caught most of my bugs.

**Comment by NoraLoose** [comment]
At the same time they are the most annoying tests to maintain if you change small things in the code (like a different interpolation method) that make the expected values change. But at least we can keep track of changes in the input fields to ROMS. This is the major purpose of ROMS-Tools (at least of `roms_tools.setup`), so I think in this case these tests are important.

**Comment by TomNicholas** [comment]
Then perhaps we should be saving very small output files as regression tests.

**Comment by NoraLoose** [comment]
Yes, that would definitely be better. I will work on this.
