### ISSUE TITLE
Mismatch between MATLAB- and python-generated grids

### ISSUE THREAD

**Issue by dafyddstephenson** [CWorthy-ocean/roms-tools#73]
There is (see screenshot) a difference between the Grid object when generated using python roms-tools vs MATLAB. Per our discussion my understanding is that topography smoothing is applied before the mask is generated, leading to the problem.

![Screenshot 2024-08-13 at 2 33 50 PM](https://github.com/user-attachments/assets/94ea9c7a-8790-4ef5-8564-d77f4343ce6a)

**Comment by NoraLoose** [comment]
Related to #66

**Comment by NoraLoose** [comment]
@nmolem looking at your MATLAB scripts, they define the mask by choosing a threshold of 0.11 meters for the dealiased interpolated bathymetry `h_dealiased`, i.e.,
- land where `h_dealiased` < 0.11 m
- ocean where `h_dealiased` > 0.11 m

Is there a deeper meaning behind that 0.11 meter threshold?

@dafyddstephenson the difference in your plot above stems from the fact that the python package simply uses a threshold of 0 meters.

**Comment by nmolem** [comment]
I don't remember why I picked 0.11 meter. Surely no deeper meaning and you can pick 0m as well.

**Comment by dafyddstephenson** [comment]
@NoraLoose got it. Well this isn't the most scientifically rigorous argument for a parameter choice but the map resulting from 0.11 definitely looks a lot more like Wales 😂🏴󠁧󠁢󠁷󠁬󠁳󠁿

**Comment by nmolem** [comment]
Sometimes, it's better to be lucky than good.

**Comment by NoraLoose** [comment]
This issue is resolved because we are now inferring the mask from a [separate coastline dataset](https://www.naturalearthdata.com/), rather than from the regridded topography together with a threshold.

This is what the improved mask looks like now for the 30 x 30 Wales grid. 

<img width="693" alt="Screenshot 2024-12-04 at 2 18 06 PM" src="https://github.com/user-attachments/assets/77c8b48c-2660-449a-adc7-877326196cdf">
